// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfddivlehdeapvxpsyha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmZGRpdmxlaGRlYXB2eHBzeWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNjY1MDcsImV4cCI6MjA3NDc0MjUwN30.CQ8pc3tkNAWNMtPdftNtl82YZM6CLJUHG4AKAcjKXZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});